openapi: 3.0.0
info:
  title: Football Match Management API
  version: 1.0.0
  description: API for managing football competitions, teams, and players.


paths:
  /competitions:
    get:
      summary: Get a list of competitions
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
          description: Page number for pagination.
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
          description: Number of items per page.
      responses:
        '200':
          description: A list of competitions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionList'
    post:
      summary: Create a new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Competition'
      responses:
        '201':
          description: Competition created

  /teams:
    get:
      summary: Get a list of teams
      parameters:
        - name: teamName
          in: query
          schema:
            type: string
          description: Filter teams by name.
        - name: page
          in: query
          required: true
          schema:
            type: integer
          description: Page number for pagination.
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
          description: Number of items per page.
      responses:
        '200':
          description: A list of teams
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamList'
    post:
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: successful operation ,Team created !

  /players:
    get:
      summary: Get a list of players
      parameters:
        - name: playerName
          in: query
          schema:
            type: string
          description: Filter players by name.
        - name: page
          in: query
          required: true
          schema:
            type: integer
          description: Page number for pagination.
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
          description: Number of items per page.
      responses:
        '200':
          description: A list of players
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerList'
    post:
      summary: Create a new player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
      responses:
        '201':
          description: Player created

components:
  schemas:
    Competition:
      type: object
      properties:
        name:
          type: string
          example: "PREMIERLEAGUE"
        location:
          type: string
          example: "SPAIN"
    CompetitionList:
        type: array
        items:
          $ref: "#/components/schemas/Competition"
    Team:
      type: object
      properties:
        name:
          type: string
          example: FC MOMOTA
        slogan:
          type: string
          example: "Hala Momota"
    TeamList:
      type: object
      properties:
        teams:
          type: array
          items:
            $ref: '#/components/schemas/Team'
    Player:
      type: object
      properties:
        name:
          type: string
          example: Ollie Watkins
        number:
          type: integer
          example: 11
        strongFoot:
          type: string
          enum:
            - Left
            - Right
          example: Right
    PlayerList:
      type: object
      properties:
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
